{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- range .Values.ingress.tls }}
  name: {{ .secretName }}
  {{- end }}
  namespace: jira
spec:
  dnsNames:
  - jira.rromani.eu
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: clustercertissuer
  privateKey:
    rotationPolicy: Always
  {{- range .Values.ingress.tls }}
  secretName: {{ .secretName }}
  {{- end }}
  usages:
  - digital signature
  - key encipherment
{{- end }}
