apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jira-data
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/raid_pool/apps-volumes/jira-data"
  persistentVolumeReclaimPolicy: Retain
